### PR TITLE
Added standard Travis config

### PR DESCRIPTION
**Pull request by helpfulrobot**
Hello!

I'm helpful robot. I noticed you had some non-standard Travis config. I think this is an improvement.

Have a nice day! [f-f-f-f-f-f-t]

### CODE REVIEW

**Comment by dhensby** [comment]
@tractorcow @helpfulrobot we seem to have a couple of problems:

SS 4.0 requires php 5.5 so we may need to remove them from the build matrix

Composer is failing to resolve the dependencies

**Comment by dhensby** [comment]
@tractorcow Travis support seems to be failing to resolve the correct branch here?

**Comment by tractorcow** [comment]
Oh, 

CORE_RELEASE must always be the branch of the framework version, sorry, not the version number. We need to use `MASTER` even if it's aliased as 4.0 in composer.

@helpfulrobot please use this information to train your neural net. :)

**Comment by dhensby** [comment]
@helpfulrobot [beep boop]

**Comment by tractorcow** [comment]
Ping @assertchris :D

**Comment by chillu** [comment]
Ping @assertchris

**Pull request closed without merging**
