### PR TITLE
Update HtmlEditorField.Translatable.js

### PR DESCRIPTION
**Pull request by flxlabs**
Should resolve Issue #214

### CODE REVIEW

**Comment by dhensby** [comment]
Thanks

**Comment by tractorcow** [comment]
Ideally we'd avoid HTML IDs as selectors, but it's not worse than it was!

**Comment by JorisDebonnet** [comment]
Could this be merged into 2.1?

**Comment by tractorcow** [comment]
Cherry pick doesn't seem to work cleanly... can you re-raise this PR on the 2.1 branch manually please?

**Comment by JorisDebonnet** [comment]
I'm confused, didn't dhensby already do this with commit 7bfece9666134f00189c8efbe1562c172fcde933 ?

**Comment by tractorcow** [comment]
That would explain why my cherry pick failed lol.

**Pull request merged**
