### PR TITLE
DOCS Added user guide (CMS 4.x)

### PR DESCRIPTION
**Pull request by camfindlay**
This will get the structure setup for 4.x user help for this module (content would further need to be addressed).

### CODE REVIEW

**Comment by chillu** [comment]
Blocked for the same reason as #217

**Comment by tractorcow** [comment]
Your screenshots still all have the old 3.2 UX. For 4.0 won't you need to update your assets?

**Comment by camfindlay** [comment]
yep we will would it be better to merge up the change and then replace the images OR wait and create this as a separate PR?

**Comment by chillu** [comment]
I think a merge up as a first step makes sense. That way Git should be able to optimise the binary blobs better, as long as you keep the filenames the same on the new 4.x screenshots.

**Comment by tractorcow** [comment]
I've merged all branches.

**Comment by tractorcow** [comment]
@cam-findlay this needs a rebase.

**Comment by dhensby** [comment]
ping @camfindlay

**Comment by robbieaverill** [comment]
Re-ping @camfindlay

**Comment by robbieaverill** [comment]
I'm going to close this, feel free to reopen if you'd like to resuscitate it =) Thanks @camfindlay!

**Pull request closed without merging**
